# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawscanresult',
            name='result',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='final_url',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='key',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='result_description',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='test',
        ),
        migrations.AddField(
            model_name='rawscanresult',
            name='data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawscanresult',
            name='data_type',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawscanresult',
            name='file_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='rawscanresult',
            name='identifier',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='backend.Scan'),
        ),
    ]
