# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170513_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='list',
        ),
        migrations.AddField(
            model_name='site',
            name='lists',
            field=models.ManyToManyField(related_name='sites', to='backend.List'),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
