# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170508_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scangroup',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ready'), (1, 'scanning'), (2, 'finish'), (3, 'error')], default=0),
        ),
    ]
