# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_scanerror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scangroup',
            name='scan_list',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='group',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='success',
        ),
        migrations.AddField(
            model_name='scan',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scanlist',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ScanGroup',
        ),
    ]
