# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170521_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawscanresult',
            old_name='data_type',
            new_name='mime_type',
        ),
    ]
