# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170515_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='ScanList',
        ),
        migrations.RenameField(
            model_name='listcolumn',
            old_name='list',
            new_name='scan_list',
        ),
        migrations.RenameField(
            model_name='listtag',
            old_name='lists',
            new_name='scan_lists',
        ),
        migrations.RenameField(
            model_name='scangroup',
            old_name='list',
            new_name='scan_list',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='lists',
            new_name='scan_lists',
        ),
        migrations.AlterUniqueTogether(
            name='listcolumn',
            unique_together=set([('name', 'scan_list'), ('scan_list', 'sort_key')]),
        ),
    ]
