# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20170523_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlist',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
