# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 16:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20170510_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='result_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
