# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20170529_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlist',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='site',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
