# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20170602_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcolumn',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='listcolumnvalue',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
