# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_scanerror_scan_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='scanlist',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
