# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20170604_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlist',
            name='pseudonym',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
