# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20170607_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='start',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
