# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20170607_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlist',
            name='last_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backend.Scan'),
        ),
        migrations.AddField(
            model_name='site',
            name='last_scan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backend.Scan'),
        ),
    ]
