# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20170619_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcolumn',
            name='sort_key',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
