# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20170621_0908'),
    ]

    operations = [
        migrations.RunSQL('''
        CREATE INDEX leaks_count
        ON backend_scanresult(jsonb_array_length("result"->'leaks'));
        '''),
    ]
