# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20170712_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='scan_lists',
            field=models.ManyToManyField(blank=True, related_name='sites', to='backend.ScanList'),
        ),
    ]
