# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20171010_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('match_type', models.CharField(choices=[('DOM', 'Entire Domain'), ('SUB', 'Subdomain only')], default='DOM', max_length=3)),
                ('contact', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
