# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_visible', models.BooleanField(default=False)),
                ('order_key', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
