# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rawscanresult_scan_host'),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlight',
            name='scan_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.ScanList'),
            preserve_default=False,
        ),
    ]
